// Generated by pd-memory catalog --typescript. Do not edit.
export const ENGINE_VERSION = "0.1.0+0f8efb4da04d8de3" as const;

export type RecallInput = {
"budget"?: number;
"folder"?: string;
"for"?: string;
"pages"?: Array<string>;
"queries"?: Array<string>;
};
export type RecallResult = {
"cost_usd"?: number;
"next": Array<string>;
"seq": number;
"text": string;
"tokens": number;
"truncated": boolean;
};

export type BriefInput = {
"budget"?: number;
"compose"?: boolean;
"folder"?: string;
"include_global"?: boolean;
"page"?: string;
"since"?: number;
};
export type BriefResult = {
"cost_usd"?: number;
"next": Array<string>;
"seq": number;
"text": string;
"tokens": number;
"truncated": boolean;
};

export type OpenInput = {
"evidence"?: boolean;
"full"?: boolean;
"history"?: boolean;
"id": string;
};
export type OpenResult = ({
"authority": "user" | "agent" | "third_party" | "unknown";
"body": (string | null);
"claimant": (string | null);
"confidence": number;
"contributions": Array<number>;
"durability": (number | null);
"entered": string;
"evidence": Array<string>;
"forgotten": (number | null);
"forgotten_reason"?: string;
"happened": (string | null);
"history"?: Array<{
"actor": string;
"created": string;
"kind": string;
"payload": {
[key: string]: unknown;
};
"seq": number;
}>;
"id": string;
"kind": "observation";
"line": string;
"observation_kind": string;
"pages": Array<string>;
"predecessors"?: Array<{
[key: string]: string;
}>;
"replaced_by": (string | null);
"replacement_chain"?: Array<string>;
"seq": number;
"sources": Array<{
"id": string;
"kind": string;
}>;
"weight": number;
} | {
"aliases": Array<string>;
"category": string;
"id": string;
"kind": "page";
"line": (string | null);
"observations": Array<{
"happened": (string | null);
"has_body": boolean;
"id": string;
"line": string;
"seq": number;
}>;
"parent": (string | null);
"replaced_by": (string | null);
"seq": number;
"slug": string;
"subpages": Array<{
"line": (string | null);
"slug": string;
}>;
"weight": number;
} | {
"actor": string;
"chunks": Array<{
"id": string;
"line": string;
}>;
"created": string;
"digest"?: string;
"entry_kind": string;
"id": string;
"kind": "source";
"next"?: string;
"participants"?: Array<string>;
"previous"?: string;
"source": {
[key: string]: unknown;
};
} | {
"context": string;
"id": string;
"kind": "chunk";
"next"?: string;
"previous"?: string;
"source": string;
"text": string;
} | {
"children": Array<string>;
"citations": Array<string>;
"cited"?: Array<{
[key: string]: unknown;
}>;
"created": string;
"headline": string;
"id": string;
"kind": "timeline";
"node_kind": string;
"parent": string;
"parent_available": boolean;
"seq": number;
"text": string;
});

export type BrowseInput = {
"folder"?: string;
"id"?: string;
"limit"?: number;
"offset"?: number;
"period"?: "day" | "week" | "month" | "year";
"view"?: "pages" | "page" | "history";
};
export type BrowseResult = {
"children"?: Array<{
"category"?: string;
"happened"?: (string | null);
"id": string;
"kind": "page" | "observation" | "timeline";
"line": (string | null);
"parent"?: (string | null);
}>;
"items": Array<{
"category"?: string;
"happened"?: (string | null);
"id": string;
"kind": "page" | "observation" | "timeline";
"line": (string | null);
"parent"?: (string | null);
}>;
"more": boolean;
"page"?: {
"category"?: string;
"happened"?: (string | null);
"id": string;
"kind": "page" | "observation" | "timeline";
"line": (string | null);
"parent"?: (string | null);
};
};

export type NoteInput = {
"actor": "user" | "agent";
"body"?: (string | null);
"claimant"?: (string | null);
"confidence"?: number;
"durability"?: (number | null);
"happened"?: (string | null);
"kind"?: "fact" | "question" | "commitment";
"line": string;
"pages": Array<string>;
"wait"?: boolean;
"weight"?: number;
};
export type NoteResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"status": string;
"submitted": {
"reused": boolean;
"seq": number;
"status": string;
};
};

export type EditInput = {
"actor": "user" | "agent";
"authority"?: "user" | "agent" | "third_party" | "unknown";
"body"?: (string | null);
"claimant"?: (string | null);
"confidence"?: number;
"durability"?: (number | null);
"happened"?: (string | null);
"id": string;
"kind"?: "fact" | "question" | "commitment";
"line"?: string;
"merge_into"?: string;
"pages"?: Array<string>;
"parent"?: string;
"reason": string;
"supersede"?: boolean;
"wait"?: boolean;
"weight"?: number;
};
export type EditResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"status": string;
"submitted": {
"reused": boolean;
"seq": number;
"status": string;
};
};

export type ForgetInput = {
"actor": "user" | "agent";
"id": string;
"reason": string;
"wait"?: boolean;
};
export type ForgetResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"status": string;
"submitted": {
"reused": boolean;
"seq": number;
"status": string;
};
};

export type FocusInput = {
"action": "hide" | "show";
"actor"?: "user" | "agent";
"folder": string;
"id": string;
"wait"?: boolean;
};
export type FocusResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"status": string;
"submitted": {
"reused": boolean;
"seq": number;
"status": string;
};
};

export type IngestInput = {
"actor"?: string;
"dialogue_json"?: boolean;
"external_id"?: string;
"happened"?: string;
"home"?: string;
"kind"?: string;
"label"?: string;
"manifest"?: string;
"metadata_json"?: string;
"path"?: string;
"session"?: string;
"stdin"?: boolean;
"wait"?: boolean;
};
export type IngestResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"status": string;
"submitted": Array<{
"reused": boolean;
"seq": number;
"status": string;
}>;
};

export type ImportSessionsInput = {
"after"?: string;
"claude_code"?: Array<string>;
"codex"?: Array<string>;
"dry_run"?: boolean;
"pi"?: Array<string>;
"routes"?: string;
"user_name"?: string;
"wait"?: boolean;
};
export type ImportSessionsResult = {
"fold"?: {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};
"import": {
"assistantCharacters": number;
"characters": number;
"dry_run": boolean;
"files": number;
"messages": number;
"reused": number;
"seqs": Array<number>;
"skipped": number;
"submitted": number;
"userCharacters": number;
};
};

export type WorkerInput = {

};
export type WorkerResult = {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};

export type StatusInput = {

};
export type StatusResult = {
"cost_usd": number;
"entries": Array<{
"attempts": number;
"error": (string | null);
"kind": string;
"seq": number;
"status": string;
}>;
"maintenance_errors": Array<{
"created": string;
"error": string;
"id": string;
}>;
};

export type RetryInput = {
"seq"?: number;
};
export type RetryResult = {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};

export type CapturedSessionEntriesInput = {
"session": string;
};
export type CapturedSessionEntriesResult = {
"entry_ids": Array<string>;
"session": string;
};

export type MaintainInput = {

};
export type MaintainResult = {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};

export type RebuildInput = {

};
export type RebuildResult = {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};

export type ReindexInput = {

};
export type ReindexResult = {
"busy"?: boolean;
"cost_usd": number;
"failed": Array<number>;
"maintenance": {
"built": Array<string>;
"cost_usd": number;
"failed": Array<{
"error": string;
"id": string;
}>;
};
"processed": Array<number>;
};

export type DoctorInput = {
"live"?: boolean;
};
export type DoctorResult = {
"base_url": string;
"cost_usd"?: number;
"credential_env": string;
"credential_set": boolean;
"embedding_credential_set": boolean;
"embedding_model": string;
"embedding_provider": string;
"live"?: {
[key: string]: unknown;
};
"model": string;
"provider": string;
"retention_policy": string;
"retention_verified": boolean;
"service_tier": string;
"store": boolean;
"workspace": string;
};

export type StatsInput = {

};
export type StatsResult = {
"chunks": number;
"contributions": number;
"cost_usd": number;
"evidence": number;
"model_calls": Array<{
"calls": number;
"cost_usd": number;
"model": string;
"phase": string;
"tier": string;
}>;
"observations": number;
"pages": number;
"views": number;
};

export type CatalogResult = {
"commands": Array<{
"description": string;
"inputSchema": {
[key: string]: unknown;
};
"name": string;
"resultSchema": {
[key: string]: unknown;
};
}>;
"operators": Array<{
"description": string;
"inputSchema": {
[key: string]: unknown;
};
"name": string;
"resultSchema": {
[key: string]: unknown;
};
}>;
"version": string;
};

export interface Commands {
"recall": { input: RecallInput; result: RecallResult };
"brief": { input: BriefInput; result: BriefResult };
"open": { input: OpenInput; result: OpenResult };
"browse": { input: BrowseInput; result: BrowseResult };
"note": { input: NoteInput; result: NoteResult };
"edit": { input: EditInput; result: EditResult };
"forget": { input: ForgetInput; result: ForgetResult };
"focus": { input: FocusInput; result: FocusResult };
"ingest": { input: IngestInput; result: IngestResult };
"import sessions": { input: ImportSessionsInput; result: ImportSessionsResult };
"worker": { input: WorkerInput; result: WorkerResult };
"status": { input: StatusInput; result: StatusResult };
"retry": { input: RetryInput; result: RetryResult };
"captured-session-entries": { input: CapturedSessionEntriesInput; result: CapturedSessionEntriesResult };
"maintain": { input: MaintainInput; result: MaintainResult };
"rebuild": { input: RebuildInput; result: RebuildResult };
"reindex": { input: ReindexInput; result: ReindexResult };
"doctor": { input: DoctorInput; result: DoctorResult };
"stats": { input: StatsInput; result: StatsResult };
"catalog": { input: Record<string, never>; result: CatalogResult };
}
export type Command = keyof Commands;
